# Generated by Django 5.2.7 on 2025-11-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='average_salary',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='career',
            name='required_skills',
            field=models.ManyToManyField(blank=True, related_name='required_for_careers', to='recommender.skill'),
        ),
    ]
