# Generated by Django 5.2.7 on 2025-11-09 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0002_career_average_salary_alter_career_required_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='average_salary',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
